apiVersion: v1
kind: Service
metadata:
  name: books
  labels:
    name: books
    app: books
spec:
  selector:
    name: books 
  type: NodePort
  ports:
   - name: http
     port: 4545
     targetPort: 4545
     protocol: TCP
