apiVersion: v1
kind: Pod
metadata:
  name: books
  labels:
    name: books
    app: books
spec: 
  containers: 
    - image: ramyacodes/books
      name: books
      ports: 
        - containerPort: 4545
